In [1]:
%matplotlib inline


What is PyTorch?
================

It’s a Python based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

Tensors
^^^^^^^

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [2]:
from __future__ import print_function
import torch

In [3]:
torch.__version__

'0.4.0'

Construct a 5x3 matrix, uninitialized:



In [4]:
x = torch.empty(5, 3)
print(x)

tensor([[ 2.1414e-25,  4.5647e-41, -9.5769e+14],
        [ 3.0962e-41, -1.1571e-07,  4.5646e-41],
        [-1.1571e-07,  4.5646e-41, -1.1936e-07],
        [ 4.5646e-41, -1.1590e-07,  4.5646e-41],
        [-1.1970e-07,  4.5646e-41, -1.1571e-07]])


Construct a randomly initialized matrix:



In [5]:
x = torch.rand(5, 3)
print(x)

tensor([[ 0.8304,  0.9008,  0.5448],
        [ 0.7934,  0.8707,  0.5265],
        [ 0.9872,  0.6703,  0.4366],
        [ 0.7256,  0.2846,  0.4702],
        [ 0.0682,  0.0473,  0.9285]])


Construct a matrix filled zeros and of dtype long:



In [7]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]])


Construct a tensor directly from data:



In [8]:
x = torch.tensor([5.5, 3])
print(x)

tensor([ 5.5000,  3.0000])


or create a tensor basing on existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [9]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]], dtype=torch.float64)
tensor([[ 1.2328, -0.2477, -1.0553],
        [-0.8336, -2.1149,  0.2893],
        [ 0.1310,  0.2767, -0.4151],
        [-1.7270,  0.4051,  0.7890],
        [-0.8924, -0.5872,  0.4320]])


Get its size:



In [10]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

Operations
^^^^^^^^^^
There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1



In [11]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 2.2045,  0.4300, -0.0692],
        [-0.3687, -1.4077,  0.4079],
        [ 0.1333,  0.6848, -0.1804],
        [-0.8511,  0.9396,  1.2093],
        [-0.7109, -0.1898,  0.4776]])


Addition: syntax 2



In [12]:
print(torch.add(x, y))

tensor([[ 2.2045,  0.4300, -0.0692],
        [-0.3687, -1.4077,  0.4079],
        [ 0.1333,  0.6848, -0.1804],
        [-0.8511,  0.9396,  1.2093],
        [-0.7109, -0.1898,  0.4776]])


Addition: providing an output tensor as argument



In [13]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 2.2045,  0.4300, -0.0692],
        [-0.3687, -1.4077,  0.4079],
        [ 0.1333,  0.6848, -0.1804],
        [-0.8511,  0.9396,  1.2093],
        [-0.7109, -0.1898,  0.4776]])


Addition: in-place



In [14]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 2.2045,  0.4300, -0.0692],
        [-0.3687, -1.4077,  0.4079],
        [ 0.1333,  0.6848, -0.1804],
        [-0.8511,  0.9396,  1.2093],
        [-0.7109, -0.1898,  0.4776]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



In [15]:
print(x[:, 1])

tensor([-0.2477, -2.1149,  0.2767,  0.4051, -0.5872])


Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [16]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [17]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([ 1.0417])
1.041677474975586


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <http://pytorch.org/docs/torch>`_.

NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations, and changing one will change the other.

Converting a Torch Tensor to a NumPy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [18]:
a = torch.ones(5)
print(a)

tensor([ 1.,  1.,  1.,  1.,  1.])


In [19]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.



In [20]:
a.add_(1)
print(a)
print(b)

tensor([ 2.,  2.,  2.,  2.,  2.])
[2. 2. 2. 2. 2.]


Converting NumPy Array to Torch Tensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
See how changing the np array changed the Torch Tensor automatically



In [21]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([ 2.,  2.,  2.,  2.,  2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [22]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

/home/zhiqiang/anaconda3/lib/python3.6/site-packages/torch/cuda/__init__.py:116: UserWarning: 
    Found GPU0 NVS 315 which is of cuda capability 2.1.
    PyTorch no longer supports this GPU because it is too old.
    
  warnings.warn(old_gpu_warn % (d, name, major, capability[1]))


RuntimeError: cuda runtime error (8) : invalid device function at /pytorch/aten/src/THC/generic/THCTensorMath.cu:15