In [54]:
import numpy as np
import torch 
import torch.nn.functional as F
import torch.nn as nn
from torch.autograd import Variable

%matplotlib inline

In [55]:
input = torch.randn(3, 5, requires_grad=True)
target = torch.randint(5, (3,), dtype=torch.int64)

In [56]:
input

tensor([[ 0.5462,  0.8520, -0.0598,  0.5314, -0.5981],
        [ 0.0007,  0.4675,  1.3673, -0.3503, -0.1712],
        [ 0.3858,  1.2548,  1.1333, -0.9658, -0.3106]])

In [57]:
target

tensor([ 3,  2,  4])

In [58]:
loss = F.cross_entropy(input, target)
loss.backward()

loss

tensor(1.5672)

In [59]:
loss = nn.CrossEntropyLoss()

output = loss(input, target)
output.backward()

output

tensor(1.5672)

In [60]:
input = torch.randn((3, 2), requires_grad=True)
target = torch.rand((3, 2), requires_grad=False)

In [61]:
input

tensor([[ 1.0707,  1.2255],
        [-1.2017, -0.6341],
        [-1.3924,  0.3612]])

In [62]:
target

tensor([[ 0.4091,  0.4762],
        [ 0.2096,  0.2924],
        [ 0.1540,  0.4049]])

In [63]:
loss = F.binary_cross_entropy(F.sigmoid(input), target)
loss.backward()

loss

tensor(0.6888)

In [64]:
input

tensor([[ 1.0707,  1.2255],
        [-1.2017, -0.6341],
        [-1.3924,  0.3612]])

In [65]:
target

tensor([[ 0.4091,  0.4762],
        [ 0.2096,  0.2924],
        [ 0.1540,  0.4049]])

In [66]:
F.sigmoid(input)

tensor([[ 0.7447,  0.7730],
        [ 0.2312,  0.3466],
        [ 0.1990,  0.5893]])

In [67]:
x = Variable(torch.randn(10, 3))
y = Variable(torch.FloatTensor(10, 3).random_(2))

# double the loss for class 1
class_weight = torch.FloatTensor([1.0, 2.0, 1.0])
# double the loss for last sample
element_weight = torch.FloatTensor([1.0]*9 + [2.0]).view(-1, 1)
element_weight = element_weight.repeat(1, 3)

bce_criterion = nn.BCEWithLogitsLoss(weight=None, reduce=False)
multi_criterion = nn.MultiLabelSoftMarginLoss(weight=None, reduce=False)

bce_criterion_class = nn.BCEWithLogitsLoss(weight=class_weight, reduce=False)
multi_criterion_class = nn.MultiLabelSoftMarginLoss(weight=class_weight, reduce=False)

bce_criterion_element = nn.BCEWithLogitsLoss(weight=element_weight, reduce=False)
multi_criterion_element = nn.MultiLabelSoftMarginLoss(weight=element_weight, reduce=False)

bce_loss = bce_criterion(x, y)
multi_loss = multi_criterion(x, y)

bce_loss_class = bce_criterion_class(x, y)
multi_loss_class = multi_criterion_class(x, y)

bce_loss_element = bce_criterion_element(x, y)
multi_loss_element = multi_criterion_element(x, y)

print(bce_loss - multi_loss)
print(bce_loss_class - multi_loss_class)
print(bce_loss_element - multi_loss_element)

tensor(1.00000e-07 *
       [[ 1.1921,  0.0000, -0.2980],
        [ 0.2980, -0.2980, -2.3842],
        [ 0.0000,  0.5960,  0.0000],
        [-0.2980,  0.2980,  0.5960],
        [ 0.0000,  0.0000,  0.1490],
        [-1.1921,  0.0000,  0.5960],
        [ 0.0000,  2.3842, -1.1921],
        [ 1.1921,  0.0000,  0.2980],
        [ 0.0000,  1.1921,  1.1921],
        [ 0.0000,  0.5960,  0.0000]])
tensor(1.00000e-07 *
       [[ 1.1921,  0.0000, -0.2980],
        [ 0.2980, -0.5960, -2.3842],
        [ 0.0000,  1.1921,  0.0000],
        [-0.2980,  0.5960,  0.5960],
        [ 0.0000,  0.0000,  0.1490],
        [-1.1921,  0.0000,  0.5960],
        [ 0.0000,  4.7684, -1.1921],
        [ 1.1921,  0.0000,  0.2980],
        [ 0.0000,  2.3842,  1.1921],
        [ 0.0000,  1.1921,  0.0000]])
tensor(1.00000e-07 *
       [[ 1.1921,  0.0000, -0.2980],
        [ 0.2980, -0.2980, -2.3842],
        [ 0.0000,  0.5960,  0.0000],
        [-0.2980,  0.2980,  0.5960],
        [ 0.0000,  0.0000,  0.1490],
        [-