In [1]:
import torch
import numpy as np

In [2]:
np_data = np.arange(6).reshape((2, 3))

torch_data = torch.from_numpy(np_data)

In [5]:
print('numpy', np_data)
print('torch', torch_data)

numpy [[0 1 2]
 [3 4 5]]
torch tensor([[ 0,  1,  2],
        [ 3,  4,  5]])


In [6]:
tensor2array = torch_data.numpy()

print('tensor 2 array', tensor2array)

tensor 2 array [[0 1 2]
 [3 4 5]]


In [10]:
#abs
data = np.array([-1, -2, 1, 2])

tensor = torch.FloatTensor(data)

torch.abs(tensor)

tensor([ 1.,  2.,  1.,  2.])

In [11]:
data.dot(data)

10

In [12]:
tensor.dot(tensor)

tensor(10.)

In [15]:
data = [[1, 2], [3, 4]]
tensor = torch.FloatTensor(data)

In [16]:
np.matmul(data, data)

array([[ 7, 10],
       [15, 22]])

In [17]:
torch.mm(tensor, tensor)

tensor([[  7.,  10.],
        [ 15.,  22.]])

In [20]:
from torch.autograd import Variable

In [21]:
tensor = torch.FloatTensor([[1,2], [3,4]])

In [34]:
variable = Variable(tensor, requires_grad=True)

In [35]:
print(variable.grad)

None


In [36]:
print(variable)

tensor([[ 1.,  2.],
        [ 3.,  4.]])


In [37]:
t_out = torch.mean(tensor*tensor)

v_out = torch.mean(variable*variable)

In [38]:
print(t_out)
print(v_out)

tensor(7.5000)
tensor(7.5000)


In [39]:
v_out.backward()

In [41]:
print(variable)
print(variable.grad)
print(variable.data)
print(variable.data.numpy())

tensor([[ 1.,  2.],
        [ 3.,  4.]])
tensor([[ 0.5000,  1.0000],
        [ 1.5000,  2.0000]])
tensor([[ 1.,  2.],
        [ 3.,  4.]])
[[1. 2.]
 [3. 4.]]


# 激励函数
relu

sigmod

tanh

In [43]:
import torch
import torch.nn.functional as F
from torch.autograd import Variable
import matplotlib

%matplotlib inline

In [ ]:
# fake data
x = torch.linspace(-5, 5, 200) # x data (tensor), shape = (100, 1)
x = Variable(x)
x_np = x.data.numpy()